### ISSUE TITLE
Bad Credentials error

### ISSUE THREAD

**Issue by shalinikat** [mageviper/module-dpd#3]
{"0":"Bad credentials","1":"<pre>#1 DpdConnect\\Sdk\\Resources\\Authentication->processRequest(array(401, '{\"code\":401,\"mes...')) called at [vendor\/dpdconnect\/php-sdk\/src\/Resources\/Authentication.php:61]\n#2 

I got this error. May I know what causes this error.

**Comment by marcinsdance** [comment]
This might be due to bad or missing credentials @shalinikat . Please double check if you have the correct credentials in your configuration.

**Comment by shalinikat** [comment]
Yes the details are correct. Earlier it was working but all of sudden
stopped working
https://www.keukenkiosk.nl/
you can check the issue on the checkout page.

**Comment by marcinsdance** [comment]
Last time this module changed was about 2 years ago @shalinikat . Something must have changed on your end?

**Comment by shalinikat** [comment]
What do you suggest in this case , how can I fix this issue?

**Comment by taurthil** [comment]
Hi, please tell me DM if you have that problem now on admin@mageviper.com
